### ISSUE TITLE
option to clutter/group icons from other active extensions of our selection into one icon in the panel to save some space

### ISSUE THREAD

**Issue by pickybl2020** [fthx/babar#10]
how about an option to clutter/group icons from other active extensions of our selection into one icon in the panel to save some space.

that would extra beneficial for those of us using small monitors on portrait mode and generally have a cleaner interface

this feature may be from another extension ( which after some research,I couldn't find- maybe someone here knows? )
or the same that would really make a good match

**Comment by fthx** [comment]
Do you reach the middle-panel (date) limit with tasks icons ?
Do you use the "reduce padding" option of BaBar ?
What extensions do use some space in the left-panel ?

**Comment by pickybl2020** [comment]
> Do you reach the middle-panel (date) limit with tasks icons ?
> Do you use the "reduce padding" option of BaBar ?
> What extensions do use some space in the left-panel ?

1. when on portrait mode: yes - on both left and right side
2. just used it but as I said above its not enough for portrait mode
3. on the left: babar, openweather, time++, Places Status Indicator but I'm referring to both sides

there quite a few times where grouping/organizing some extension icons that are "idle" meaning they don't  display on the fly some kind of info ( e.g. speed, latency, weather...etc ) but from time to time they're handy to access right away like the extension "Notes".

maybe a solution could be grouping the extension-panel-icons of our choice into some kind of a drop-down menu/drawer like the favourites on babar or another one

**Comment by fthx** [comment]
Ok I understand your needs, but I won't do that inside BaBar. That's simply not the goal of this extension.
Grouping BaBar tasks into a button does not look useful IMHO because you would need to do as many clicks than GS native behaviour.
