### ISSUE TITLE
Some touchscreen controls don't work 

### ISSUE THREAD

**Issue by pickybl2020** [fthx/babar#13]
choosing workspaces or active windows do work,

BUT touchscreen controls like **"clicking" at one of the favorite apps or the activities/app-list** don't work with touch

**Comment by fthx** [comment]
I just tested it on a touchscreen laptop and I get exactly the opposite: favs are ok (menu and items) but not apps/ws icons in panel.
Please confirm this or not.

**Comment by fthx** [comment]
Ok I basically can handle touch but I don't know how to handle long touch or double touch.

**Comment by pickybl2020** [comment]
I can see whats you mean... you're right

if i keep my finger on the screen and slide down.. kind of a workaround but.. it works just fine

thanks

**Comment by fthx** [comment]
Could you test the new dev version (in this GitHub) with drand and drop?
There are some changes in button event handling, so it may be worse or better...
:-)

**Comment by pickybl2020** [comment]
ive just seen the message

yeah it works... although for touch controls there should be an option making the icons a bit bigger for easier control 
at least for smaller screens like 14"

thank you so much

**Comment by fthx** [comment]
Yes I agree. The problem is that setting the panel's height or the task icons size is very easy, but I would have to modify the size of all elements in panel too... Why not, but it would need some work.

Please open a new bug for that if you're interested.
