### ISSUE TITLE
Keyboard layout window not listed

### ISSUE THREAD

**Issue by wooque** [fthx/babar#18]
When you click on "Show Keyboard Layout" in layout switcher widget it opens up new window that is not shown in list.

**Comment by wooque** [comment]
I investigated and window type is DIALOG, so maybe add it to whitelist also.

**Comment by fthx** [comment]
Thanks.
I just was starting to execute lg to pick window type!
Could you add DIALOG to whitelist? I made this whitelist to ease adding some types, so that's the moment to do that. ;-)

If you don't experience some downsides after a few days, we could add this type. I will test this too.

**Comment by fthx** [comment]
Please note that I usually do not define many layouts, so I never saw this...
And it's intended that you cannot minimize the layout dialog: I test if the window can be minimized before doing this.
```
_on_button_press(widget, event, w_box, ws_index, w) {
    	// left-click: toggle window
    	if (event.get_button() == 1) {
			if (w.has_focus() && !Main.overview.visible) {
				if (w.can_minimize()) {
		   			w.minimize();
		   		}
		   	} else {	
				w.activate(global.get_current_time());
			}
			if (Main.overview.visible) {
				Main.overview.hide();
			}
			if (!w.is_on_all_workspaces()) {
				WM.get_workspace_by_index(ws_index).activate(global.get_current_time());
			}
		}
```

**Comment by wooque** [comment]
yes, I added DIALOG type and will report if any problems arise from that change

**Comment by fthx** [comment]
Can we close this?

**Comment by wooque** [comment]
well I didn't experience any problems from adding DIALOG to whitelist types, so I think it's safe to add

**Comment by fthx** [comment]
Ok, it will be included in the next upload. I don't make this now because we have some GS 40 CSS changes in discussion.
