### ISSUE TITLE
Feature request: Improve tasks visualization

### ISSUE THREAD

**Issue by frandieguez** [fthx/babar#20]
Hi!

there are some things that bothers me.

![image](https://user-images.githubusercontent.com/4584/112801367-1a302880-9071-11eb-9c37-a0af23ceda77.png)

 - When I have multiple Chrome windows open, the task shows all of them. Could it be possible to group them together into one element
- After grouping them together, could we show a popover window which shows a list, or even better a preview, of those windows?

I'm thinking something similar to what dash-to-panel does which would be perfect, but dash-to-panel IMHO does too many things in one extension
![image](https://user-images.githubusercontent.com/4584/112802225-3a141c00-9072-11eb-8b22-3b48aa7f6973.png)

Regards

**Comment by fthx** [comment]
When I thought to that, I decided to run for a simple and light solution with immediate tooltip, to allow fast browse of tasks.
Grouping is clearly possible but going for thumbnails pop-ups would need some hard work (cf. Dash to Panel).

**Comment by fthx** [comment]
(I've just read your update.)
Well, a simple menu like in GS dash could be more thematic & light? I agree that's no better, but I don't want BaBar to be a Dash-to-Panel clone (and I agree with you that DtP does too many things, that cause bugs).

**Comment by fthx** [comment]
Now that drag and drop is working (what an effort, there is no doc, happily I was helped to begin this but that was not the end of the story!), we have a free right-click.
Could you tell me what you would do with this right-click? I think to your window preview?

**Comment by fthx** [comment]
Ok, window preview do work now with a right-click. Not published yet.
Would you need these previews to be draggable anywhere? resizeable?
Would you like to have the possibility to display many previews at the same time (windows on top)?

**Comment by fthx** [comment]
Ok, previews are here with v45.
Feel free to reopen for task grouping, if it's still wanted.
