### ISSUE TITLE
Better methode to select Icons for taskbar

### ISSUE THREAD

**Issue by GaVenga** [fthx/babar#22]
I would like to have something like an "icon-chooser" instead of fixed path for the icons...

**Comment by GaVenga** [comment]
/usr/share/icons/Papirus-Dark/symbolic/actions/view-app-grid-symbolic
/usr/share/icons/Papirus/symbolic/actions/view-app-grid-symbolic
/usr/share/icons/Adwaita/actions/...
/usr/share/icons/Adwaita/24x24/actions
/usr/share/icons/Adwaita/96x96/actions
/usr/share/icons/Adwaita/48x48/...
/usr/share/icons/Adwaita/scalable/...
/usr/share/icons/Adwaita/16x16/...
/usr/share/icons/Adwaita/32x32/...
/usr/share/icons/Adwaita/64x64/...
(the Icon "Babar" uses is too small on a screen of 2560x1440)

**Comment by fthx** [comment]
It's a SVG icon, so I don't understand this point.
Maybe give me a screenshot?
