### ISSUE TITLE
ability to reorder task icons on panel

### ISSUE THREAD

**Issue by vsudakov** [fthx/babar#23]
ability to reorder task icons on panel by keyboard shortcut (e.g. `Super + Shift + Left/Right`)

**Comment by fthx** [comment]
Sorry but I won't do that.
Something like this could eventually happen, with drag and drop for workspace switch for tasks.

The way this extension works makes it difficult to do. The tasks are simply redisplayed when task bar is redrawn. So their order is creation time based (and favorites if selected in options). But no order information is stored inside BaBar between these redraws.

**Comment by vsudakov** [comment]
@fthx thank you for a quick reply! it makes sense!

yeah - now I'm thinking that if I split my tasks to **more** workspaces - they will be grouped better.

this can be a workaround for me, thanks!

**Comment by fthx** [comment]
You can test drag and drop from this GitHub's code (warning: please change all the files, not only extension.js).
That does not fit what you asked for, but it's quite handy! You can DnD favorites too, to any existent workspace.
