### ISSUE TITLE
[MISC] AUR package and License

### ISSUE THREAD

**Issue by starmatt** [fthx/babar#24]
Hello.

First of all, thanks for your work, BaBar is very useful to me!

I didn´t know where else to contact you. I wanted to let you know I´ve created an [AUR package of your extension](https://aur.archlinux.org/packages/gnome-shell-extension-babar).

For best practice purposes, have you considered using a license under which to submit your extension?

Thanks for your attention.

**Comment by fthx** [comment]
Hi,

I've just added a license file (GPL v3).
Thanks for packaging this extension!
