### ISSUE TITLE
Feature: Favorite icons match task icons size

### ISSUE THREAD

**Issue by wooque** [fthx/babar#26]
I noticed that icons in Favorites menu are smaller than before, it would be nice if their size matched size of icons in taskbar.

![Screenshot from 2021-04-20 02-59-39](https://user-images.githubusercontent.com/1936195/115321793-d9fe2a80-a184-11eb-8cdb-3104ae087ca1.png)

**Comment by fthx** [comment]
Yes, I did refactor the favorites menu code some times ago, using now the integrated GJS function that make a combo menu item (icon + text). So I cannot change this, the icon size is handled by gnome shell.
Before that, I manually created each item with an icon and text in a BoxLayout...

**Comment by fthx** [comment]
About styling: what is your opinion on the new more rounded setup?
Question: when you right-click on a window button, you get window preview. There is a 1px frame. Could you tell me if you feel better with no frame? It would have the advantage to not have these window's shadows margins for non full-screen windows. You have to modify the end of css file like this (= comment all this section):

```
.window-thumbnail {
  /*border: 1px solid rgba(67, 67, 67, 0.7);
  border-radius: 2px;
  background-color: rgba(204, 204, 204, 0.7);*/
}
```

**Comment by wooque** [comment]
It looks ok to me
