### ISSUE TITLE
Click on workspace name: left = switch only, middle and right = switch and show overview

### ISSUE THREAD

**Issue by sluedecke** [fthx/babar#29]
To quickly switch between workspaces the clicks on workspace names could be differentiated between: switch to workspace and show overview (current behaviour for any mouse button) and switch only.

Right now it requires two clicks to just switch the workspace (or a single one on a task, but this is not always desired).

So the feature request is to have different behaviour in `_toggle_ws(ws_index)` based on the mouse button.

**Comment by sluedecke** [comment]
A patch like this might do the trick
[patch-workspace-buttons-switch.txt](https://github.com/fthx/babar/files/6423639/patch-workspace-buttons-switch.txt)

**Comment by fthx** [comment]
That's of course a possibility. I thought about that when I created these workspaces buttons. But I don' t see a case in which this new behavior could be better:
- when you switch to a non-empty ws, you can click on a task directly ;
- when you switch to an empty ws, it's to launch a new app, so overview is better.

So I'm open if I see here that the new behavior allows easier clicks.

**Comment by sluedecke** [comment]
It probably depends on personal preference.

case 1: sometimes I don't want to raise a specific task, just switch to the workspace.  For that the workspace button is easier to target with the mouse.  Personally I appreciate and use both options: simply switch to a WS (e.g. to return to a browsing session or a video player) and switch to a specific task on a WS (e.g. to raise a tool window from a bunch of open windows, all parked on a "tool" workspace)

case 2: I agree for default configurations.  Since I also use the "dash to dock" extension, I have the dock with my favorites shown on empty desktops anyways.  Also I can have a look at my wallpaper in full, which is a welcome 'break' moment from time to time before I open the next task (yes, the overview shows it too, but it is not at full size)

Thinking about it, I make a lot of use of the workspace buttons and they are a lot easier to hit for me.  In terms of visual categories it also makes sense to me: thinking "switch workspace" maps to "target a workspace" and the buttons are clearly distinctive from task buttons.  Thinking "switch to task XYZ" maps to target a specific task icon which are visually distinctive, too.

**Comment by fthx** [comment]
Ok I will make a preference.

**Comment by sluedecke** [comment]
Great, sounds good, thanks a lot!

**Comment by fthx** [comment]
https://github.com/fthx/babar/commit/ac91c58e64c82bae3c849db8e6950f0d15bcca0a

**Comment by fthx** [comment]
It's already reviewed.
So you should get a GNOME extensions update notification soon.

**Comment by sluedecke** [comment]
That was fast :)
