### ISSUE TITLE
Switching between empty workspaces does not update workspace logo

### ISSUE THREAD

**Issue by sluedecke** [fthx/babar#30]
Reproduce:

* start gnome shell with >1 named workspaces
* ensure that no tasks are running
* switch to any other workspace

Workspace logo will not be shown as active.

Patch:

[patch-workspace-update-on-switch.txt](https://github.com/fthx/babar/files/6425714/patch-workspace-update-on-switch.txt)

**Comment by fthx** [comment]
ok I'll look at this very soon.

**Comment by fthx** [comment]
https://github.com/fthx/babar/commit/d88ce3956b6aa864d8101affbe15b69868aa45f0#diff-19a9a3efb94bf1b84229bda71ab0ef5badcdbf34ba3a0c9e4152a82c569a21e6R193

Your patch does not apply when you switch workspace with keyboard shortcuts or 4 fingers swiping. So I did add a signal.

**Comment by sluedecke** [comment]
Interessting and also thanks - I really like babar, it's the last nail in KDEs coffin for me.
