### ISSUE TITLE
Toggle of "Always on visible Workspace" only reflected on additional action

### ISSUE THREAD

**Issue by sluedecke** [fthx/babar#32]
I found a 'minor' glicht in the UI behaviour:

Reproduce:
* configure babar to show workspace buttons
* open some windows
* right click on a window title and select "Always on visible Workspace"

Expected:
* window icon is moved to front of babar immediately

Observed:
* babar is updated only if something causes it to `_update_ws` like switching windows or change their maximized/minimized state

**Comment by fthx** [comment]
Ok thanks, I can reproduce. I never use this function, so I did miss that bug.

I'll have a look at what signal is necessary. I don't know if I can succeed, though, because I use global signals, not per-window ones.

**Comment by fthx** [comment]
https://github.com/fthx/babar/commit/107d0e6399e161e35a6101d160a650e0e4276729

Feel free to reopen if it's not working for you.

**Comment by fthx** [comment]
It's online now in GNOME Extensions website.
Was damn fast, thanks reviewer.

**Comment by sluedecke** [comment]
Wow, that was real quick!

But: it's not working for me.  I log into my desktop with no tasks started.  Then I start a single task (Extensions), right click the title bar and select visibility on all workspaces.

Babar is not updated directly, only after I switch workspaces or when I start an additional task.

**Comment by fthx** [comment]
I see.
I just have tested this again and it's 100 % working on Ubuntu 20.04 (GS 3.36) but not on my Fedora 34 VM (GS 40).

**Comment by fthx** [comment]
Well, I've got a solution:
this._windows_changed = this.window_tracker.connect('tracked-windows-changed',  this._update_ws.bind(this));
as a new signal.

Buuuut: it redraws much more times the task bar. So I have to investigate.

**Comment by fthx** [comment]
in GS 3.36 current code is working only in your case.
If there are some other apps open, task bar is not updated!
Quite odd.

**Comment by sluedecke** [comment]
It is.  Thanks a lot for looking into it.

I am using Arch Linux with Gnome 40 btw.

**Comment by fthx** [comment]
Ok.
I really made a redraw counter and the new signal does not really change the redraws count.
So let's go: https://github.com/fthx/babar/commit/14a26369f232336391651203b4b68355c672b1c1

I tried to not redraw the task bar too often, but it causes some glitches, as GS objects sometimes need some time to be raised or available... It remains ok, that a few redraws (only one for focus change e.g., max. 8 for any action, like launching an app).

Feel free to reopen if... ;-)

**Comment by fthx** [comment]
Please test this code. If it's ok, I'll pull it to GS extensions website. Should absolutely not introduce any bug, but I want to be sure it's ok with GS 40 (it is, as far as I tested).

**Comment by sluedecke** [comment]
Works fine for me now (version 55 from GS extensions site).  Thank you for fixing it!

**Comment by fthx** [comment]
You're welcome.
(I pushed this before your feedback since I had the time to test it in GS 40.)

If you have some BR or suggestions, don't hesitate.
