### ISSUE TITLE
Wayland issue

### ISSUE THREAD

**Issue by wooque** [fthx/babar#35]
When using GNOME on Wayland, first time window is opened it is shown faded like it's minimized, but when second window is opened, they both appear normal, and after second one is closed, so only first one is left, everything is normal.
So issue happens only when first window on workspace is opened.

**Comment by wooque** [comment]
Hmm, it does not happens always, but it happens consistently with Firefox and Code OSS, both that I set to run explicitly under Wayland instead of XWayland

**Comment by fthx** [comment]
I do use Wayland but did not experience that.
What GS version do you use?

I will use BaBar and check all that. (I do not use any extension at the moment.)

**Comment by wooque** [comment]
Latest one, 40.2.
You don't use BaBar anymore?

**Comment by fthx** [comment]
I do use BaBar (GS 3.38, Debian 11) sometimes for testing purposes. It's still maintained!
I will test it about your BR in a VM.

**Comment by wooque** [comment]
Not big deal, I won't use Wayland for now, experienced other problems with it

**Comment by fthx** [comment]
Could you confirm your BR now, evene if you don't use Wayland often?

**Comment by wooque** [comment]
Yep, tested now

**Comment by fthx** [comment]
Ok, I'll have a look, I've installed a new Ubuntu 21.10 dev VM for extensions testing with GS 40.
