### ISSUE TITLE
Scroll on extension's settings

### ISSUE THREAD

**Issue by arhayati** [fthx/babar#37]
When I open the extension's settings, I miss some items at the bottom of the window because it goes under the screen view and I can't scroll down to access them. Please put an scroll in it so we can reach all the items. I'm attaching a screenshot.
![Screenshot](https://user-images.githubusercontent.com/64958513/125467870-feb2bd72-b322-422f-9cf0-1ef7a0e36489.jpg)

**Comment by fthx** [comment]
If anyone can help, I would be happy to not having to search for a solution. It should not be complicated here.
You can post here the code to add to prefs.js, no particular need to make a PR.

**Comment by G-dH** [comment]
@fthx 2 months ago I sent you a pull request that solves this issue, if I remember correctly...

**Comment by fthx** [comment]
Ok I forgot to read it completely, I did only notice the title mentioned part.

**Comment by fthx** [comment]
Please test the new github code and tell me if all is ok to update GS extension's website.

**Comment by G-dH** [comment]
@fthx I tested the code from my PR on gnome 3.36 and 40. Now I'm out of computer.
