### ISSUE TITLE
Global menu

### ISSUE THREAD

**Issue by 0xarh** [fthx/babar#39]
Many of us miss global menu, it would be awesome if we could choose between current app menu which is the window name and a global menu. Currently, for menu we should click on the window name on top bar and do what we want but if we could have the menu items in top bar, it would be awesome.

**Comment by fthx** [comment]
Sorry, that's not in the scope of BaBar, and it (again) takes too much space in top bar.

**Comment by 0xarh** [comment]
> Sorry, that's not in the scope of BaBar, and it (again) takes too much space in top bar.

I don't think it takes more space than many window names. It can be something like a fixed space with a "..." icon for other menu items if the menu exceeds its space. And it can be enabled/disabled so people are not forced, huh?

**Comment by fthx** [comment]
What do you think about "many windows names"? Where?
Well, anyway I won't do that because I still think that there is no space enough to render all tasks (at least) and a global menu properly rendered. If a PR is made and the result is good, why not.

**Comment by 0xarh** [comment]
I think I found why I don't have space problem. I use a plugin named "Frippery Move Clock" which moves my clock from center to right. I attach a screenshot. I think you can implement that in the plugin and make space. Sorry I'm not a technical person and I don't know how to do it.
![Screenshot from 2021-07-18 19-55-45](https://user-images.githubusercontent.com/64958513/126072896-cd9a6609-18ce-4ed3-beb1-4501289da28e.png)

**Comment by fthx** [comment]
Ok but you don't have as much space as you guess. BaBar is at left of the panel. This left space is limited to the middle of the panel. It's possible to extend this left part, but that's again another GS modification.
Well, as I wrote here, I will not spend a lot of time at making global menu. There are extensions for that, I did not test if they are compatible with BaBar.
