### ISSUE TITLE
[FEAT] Hide workspace number/indicator if workspace is empty

### ISSUE THREAD

**Issue by WandersonAlves** [fthx/babar#40]
![image](https://user-images.githubusercontent.com/9141449/129291891-f4897c5e-5d0c-4fc7-add5-e412907cfc2a.png)
Workspace number 3 doesn't have any applications running. Maybe you can app some feature to hide the workspace number when the workspace is empty?

Thanks!

**Comment by fthx** [comment]
I understand that it could be thought as odd, but that's simply the GNOME behavior.
If you don't get this 3rd workspace, you cannot access this ws through BaBar.
Note that you can use static ws if you don't want this.
