### ISSUE TITLE
Add all favorites in task bar even if not launched yet

### ISSUE THREAD

**Issue by mouchimotte** [fthx/babar#48]
Hello,

It's a `feature request`.

It is possible to add the list of favorites App in the task bar, even those one are not launched yet?

Today, the behavior is, the App icon is pined in task bar while this one is running.
My desire is to have the favorites App listed (launched or not) to be able to run it in one click.

**Comment by fthx** [comment]
Hi,

That's not possible at least with the current way the extension works. Sorry.
I spedn time in Dock from Dash extension atm.

**Comment by mouchimotte** [comment]
Ok it's a pity.
Thanks for your quick response.
Thanks for your hard work on those useful extension too :D
