### ISSUE TITLE
[Feature request] Ask for preferences

### ISSUE THREAD

**Issue by Blackrucat** [fthx/babar#5]
We need options.
There are a few things that I don't like in this ADD-ON, and am not a programmer.
There are no options to change those things, like the app menu ICON, and the workspace icons, they would look better being rounded instead of squares.
I love your extensions, it is not heavy for the system.

**Comment by fthx** [comment]
Please list all the options you want to be available. Note there are some options in extension.js, at the beginning.

I'll make preferences but without UI at the moment because GNOME 40 will need gtk4 UI so it's not the moment to do something that need to be rewritten in one month or two. The prefs will be easily accessible through Dconf editor.

**Comment by Magean0** [comment]
Thanks for writing this extension. In my opinion, preferences should focus on enabling/disabling various features:
-show App Grid button OR show Activities text button OR show both
-toggle on/off Favorite Applications button
-replace Places with an icon OR leave it unchanged
-toggle on/off workspace cycling

**Comment by Blackrucat** [comment]
> Thanks for writing this extension. In my opinion, preferences should focus on enabling/disabling various features:
> -show App Grid button OR show Activities text button OR show both
> -toggle on/off Favorite Applications button
> -replace Places with an icon OR leave it unchanged

And also, an option to have rounded WORKSPACES indicators, instead of squares.

**Comment by fthx** [comment]
Ok I will make that (there are some settings already here but not available in dconf at the moment, I will add your needs).
```
// settings
var WORKSPACES_SCHEMA = "org.gnome.desktop.wm.preferences";
var WORKSPACES_KEY = "workspace-names";
var FAVORITES_ICON_NAME = 'starred-symbolic';
var PLACES_ICON_NAME = 'folder-symbolic';
var FALLBACK_ICON_NAME = 'applications-system-symbolic';
var DISPLAY_APP_GRID = true;
var ICON_SIZE = 20;
var TOOLTIP_VERTICAL_PADDING = 10;
var HIDDEN_OPACITY = 127;
var UNFOCUSED_OPACITY = 255;
var FOCUSED_OPACITY = 255;
var HIDE_APP_MENU = true;
var DISPLAY_FAVORITES = true;
var DISPLAY_TASKS = true;
var DISPLAY_PLACES_ICON = true;
```

**Comment by fthx** [comment]
Prefs will be available to test these days.
:-)
I'll ask you to test the extension before publishing it.

**Comment by fthx** [comment]
You can try the first version (not yet reviewed) with prefs here:
https://extensions.gnome.org/review/download/22238.shell-extension.zip
extract it, rename to 'babar@fthx' and replace the existing one.

Tell me if it's ok.

**Comment by fthx** [comment]
The new version is published now, you should get some update notification from GS.

**Comment by fthx** [comment]
There's a small bug (see https://github.com/fthx/babar/commit/569f75cf24abb3f548ea99e0f18e2d651a6204bd if you want to correct the code now) with desaturating icons option.
Waiting for v18+, please turn "Remove color from tasks icons" OFF. If there is already an error, just restart your session with this option turned off.

**Comment by fthx** [comment]
Well, I close this now.
Feel free to ask new prefs in new bug reports.
