### ISSUE TITLE
[Suggestion] Too much space between favorites and tasks

### ISSUE THREAD

**Issue by wooque** [fthx/babar#7]
It seems to me that there are too much space between favorites and workspaces/tasks

![Screenshot from 2021-02-15 15-32-11](https://user-images.githubusercontent.com/1936195/107959250-73516a80-6fa3-11eb-8b34-4889cd1445f0.png)

**Comment by fthx** [comment]
Yes, it's a reasonable point of view.
I waited for someone to ask, because it does not annoy me.

I did not add a spacing. It's GNOME natural spacing. But I'll look at a solution now.

**Comment by fthx** [comment]
Done: https://github.com/fthx/babar/commit/861419cb2dd7d421894d0bc91f97b5f9796c48c2
You can find the zip here too:
https://extensions.gnome.org/review/download/22276.shell-extension.zip

Please test. :-)

**Comment by wooque** [comment]
works like a charm
thanks :+1:

**Comment by fthx** [comment]
v21 avoids an error that sometimes happen when playing with some options and disabling/enabling/disabling extension.
You can find it here:
https://extensions.gnome.org/review/download/22286.shell-extension.zip
The error is harmless, especially when you don't play with options, but I advise you to update.
