### ISSUE TITLE
Babar thinks "DING" is a window

### ISSUE THREAD

**Issue by bernardelli** [fthx/babar#8]
Firstly, thank you for the simple task bar project and this current remake. I love saving screen space.

I use a extension for better desktop icons, [DING](https://extensions.gnome.org/extension/2087/desktop-icons-ng-ding/). Babar recognizes it as a window at the sticky workspace. Clicking on the right gear below shows/hides the desktop icons. 

![image](https://user-images.githubusercontent.com/9707436/108272031-750c6100-7150-11eb-895a-ccf591fcf2ec.png)

I am not sure, though, where the left gear comes from. I will try to find out later.

**Comment by bernardelli** [comment]
Just found out that the first gear only appears when I am using two monitors.

**Comment by fthx** [comment]
Thanks for reporting.
I look at this now, I think that checking more carefully the windows that have to be shown as icons will solve this. I hope that Looking Glass will tell me what type is DING window.

_FYI: The gear is the default fallback icon, if window app does not have one. It's useful too when GS create a window object but its properties are not yet accessible... Would you need a setting for this fallback icon or you don't care?_

**Comment by fthx** [comment]
Ok, done.
You can find the commit here: https://github.com/fthx/babar/commit/d3b874ef8d9c81f1f8c479855cceaf4eeb3d3148
You can also download the latest version here, before reviewing by GNOME team:
https://extensions.gnome.org/review/download/22315.shell-extension.zip

I just added DESKTOP WindowType in blacklist. And it worked, as far I can test.
Feel free to reopen if it did not solve your issue.

**Comment by fthx** [comment]
Ok, I saw that you changed icon size and that the gear did not follow that.
You can find the corrected extension here:
https://extensions.gnome.org/review/download/22318.shell-extension.zip

**Comment by bernardelli** [comment]
Just tested and the problem is gone.

**Comment by fthx** [comment]
FYI:
https://github.com/fthx/babar/issues/6#issuecomment-781943033
New options: hide dash & ww thumbnails, buttons for moving window to another ws.
I don't know how to make drag'n'drop, so it's better than nothing. :-)

**Comment by patarapolw** [comment]
Can I choose what to hide?

Currently, I need not only DING, but also Conky.

**Comment by fthx** [comment]
What is precisely your issue? Conky is displayed as a BaBar icon?
If Conky is displayed as a NORMAL typed window, I cannot do anything and this should be considered as a Conky bug.

**Comment by patarapolw** [comment]
![Screenshot from 2021-05-20 16-08-37](https://user-images.githubusercontent.com/21255931/118952031-cb728100-b985-11eb-8bc6-6d6bca4b9c0b.png)

I am only opening Brave browser.

**Comment by fthx** [comment]
Ok, so something has changed in DING too.
I try that in my Fedora 34 VM and I'll be back.

Could you check the window type of Conky (using lg) ?

**Comment by fthx** [comment]
![image](https://user-images.githubusercontent.com/23138504/118954479-18426180-b95e-11eb-8153-14abae23b7bf.png)

use the pipette

**Comment by fthx** [comment]
Ok, DING is a NORMAL window (value: 0), so I cannot do anything.
Maybe a hack, I'll see.

**Comment by patarapolw** [comment]
DING disappears in Xorg, but appear in Wayland.

![Screenshot from 2021-05-20 16-25-47](https://user-images.githubusercontent.com/21255931/118955073-93207200-b988-11eb-98b3-27bf7d096e3c.png)
![Screenshot from 2021-05-20 16-28-52](https://user-images.githubusercontent.com/21255931/118955086-94ea3580-b988-11eb-9f92-7f65e9ada2f0.png)

I am currently in Xorg.

**Comment by fthx** [comment]
Well, it will be hard, because the DING window name is:
![image](https://user-images.githubusercontent.com/23138504/118955126-b6362c00-b95e-11eb-857b-7496371df12c.png)

**Comment by fthx** [comment]
Does DING window appear in GNOME Dash?

**Comment by patarapolw** [comment]
Both GNOME and Conky, no, I think. (In Wayland)

![Screenshot from 2021-05-20 16-41-05](https://user-images.githubusercontent.com/21255931/118957012-52295d00-b98a-11eb-937f-44506b1a7c65.png)

I still hope for a Quick Fix, in `extension.js`, maybe.

**Comment by fthx** [comment]
Hmm, maybe I can investigate on some window properties (fullscreen but not minimizable e.g.) to filter displayed BaBar icons.

**Comment by fthx** [comment]
Could you check that for DING and Conky windows? : 
![image](https://user-images.githubusercontent.com/23138504/118959779-ec75aa80-b962-11eb-822b-c1bd24f43888.png)

**Comment by patarapolw** [comment]
![Screenshot from 2021-05-20 17-18-13](https://user-images.githubusercontent.com/21255931/118962356-7c314e00-b98f-11eb-8401-2c39b98ca110.png)

**Comment by fthx** [comment]
Nope, I'll include a is_skip_taskbar filter.
I'll check that very soon.

**Comment by fthx** [comment]
https://github.com/fthx/babar/commit/5445219a0fb0c5140a55afb9f4878cc7ef968704

Feel free to reopen if you still experience the issue.

**Comment by fthx** [comment]
It's online now, you should get a GNOME notification to update BaBar soon.
